name: Linter
on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout node
        uses: actions/checkout@v2

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Lint
        run: pnpm install && pnpm lint
