name: Fetch RSS Feed

on:
  workflow_dispatch:

jobs:
  fetch-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout node
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --immutable --check-cache

      - name: Fetch RSS Feed
        run: |
          npx tsx ./scripts/rss.ts
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}

      - name: Commit and push changes
        run: |
          git config --global user.email "kunshup2000@gmail.com"
          git config --global user.name "Yummy-sk"
          git checkout staging
          git checkout -b "update/rss"
          git add .
          git commit -m "Update RSS Feed"
          git push origin "update/rss"
